bad_smiles = ['Cl(=O)(=O)[O-]',
              'Cl(=O)(=O)(=O)[O-]',
              '[I-](I)I',
              'Cl(=O)(=O)[O-]',
              'CN1C(=[N+](C2=C1C=CC=C2)CCCCCCCCCCCCCC)C=2N=CSC2',
              'C(CCCCCCCCCCCCCCC)[N+]1=C(N(C2=C1C=CC=C2)C)C=2N=CSC2',
              'CN1C(=[N+](C2=C1C=CC=C2)CCCCCCCCCCCCCCCCCC)C=2N=CSC2',
              'C(CCCCCCCCCCC)[N+]1=C(N(C2=C1C=CC=C2)C)C=2N=CSC2',
              'C(CCCCCCCCC)[N+]1=C(N(C2=C1C=CC=C2)C)C=2N=CSC2',
              'CN1C(=[N+](C2=C1C=CC=C2)CCCCCCCC)C=2N=CSC2',
              'C(C)[N+](C)(C)C']
